In [1]:
# Dependencies
import json
import gmaps
import pandas as pd
import requests
from pprint import pprint
from config import gkey

# Configure gmaps
gmaps.configure(api_key=gkey)

In [2]:
city_df = pd.read_csv("Output_csv_files/city_data.csv")
city_df.head()

,City,Latitude,Longitude,Temperature,Humidity,Cloudiness,Wind Speed
0,ribeira grande,38.52,-28.70,61.54,73.0,97.0,4.70
1,punta arenas,-53.15,-70.92,41.00,80.0,20.0,13.87
2,wattegama,6.80,81.48,84.13,62.0,1.0,4.97
3,ushuaia,-54.80,-68.30,41.00,81.0,20.0,5.82
4,hobart,-42.88,147.33,53.69,58.0,75.0,20.80

In [3]:
locations = city_df[["Latitude","Longitude"]]
humid = city_df["Humidity"].astype(float)

In [4]:
# Plot Heatmap
fig = gmaps.figure(center=(51.5, -0.2), zoom_level=2)

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=humid, 
                                 dissipating=False, max_intensity=10,
                                 point_radius=1)

# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

In [5]:
vacation_df = pd.DataFrame(city_df, columns = ["City", "Temperature", "Wind Speed", "Cloudiness"])

temp_param = (vacation_df["Temperature"] <= 80) & (vacation_df["Temperature"] > 70)
wind_param = vacation_df["Wind Speed"] < 10
cloud_param = vacation_df["Cloudiness"] == 0
temp_param
vacation_df[temp_param & wind_param & cloud_param]
#len(vacation_df[temp_param & wind_param & cloud_param])

                City  Temperature  Wind Speed  Cloudiness
20   lazaro cardenas        74.05        1.63         0.0
91            dwarka        78.91        9.55         0.0
113        morondava        76.64        4.41         0.0
148            birin        71.55        4.09         0.0
231            pisco        71.76        8.05         0.0
308        bageshwar        75.25        0.54         0.0
437      miandrivazo        75.99        3.36         0.0
474        antsohihy        75.96        8.84         0.0
494         mehnagar        75.20        2.24         0.0

In [6]:
final_vacation_df = vacation_df[temp_param & wind_param & cloud_param]
final_vacation_df

                City  Temperature  Wind Speed  Cloudiness
20   lazaro cardenas        74.05        1.63         0.0
91            dwarka        78.91        9.55         0.0
113        morondava        76.64        4.41         0.0
148            birin        71.55        4.09         0.0
231            pisco        71.76        8.05         0.0
308        bageshwar        75.25        0.54         0.0
437      miandrivazo        75.99        3.36         0.0
474        antsohihy        75.96        8.84         0.0
494         mehnagar        75.20        2.24         0.0

In [7]:
hotel_df = pd.DataFrame(city_df, columns = ["City", "Latitude", "Longitude"])
hotel_df["Hotel Name"] = ""
hotel_df

               City  Latitude  Longitude Hotel Name
0    ribeira grande     38.52     -28.70
1      punta arenas    -53.15     -70.92
2         wattegama      6.80      81.48
3           ushuaia    -54.80     -68.30
4            hobart    -42.88     147.33
..              ...       ...        ...        ...
569          mehamn     71.04      27.85
570       mogadishu      2.04      45.34
571   alice springs    -23.70     133.88
572          hegang     47.40     130.37
573             vao    -22.67     167.48

[574 rows x 4 columns]

In [8]:
params = {
    "radius": 5000,
    "types": "hotel",
    "keyword": "hotel",
    "key": gkey
}
for index, row in hotel_df.iterrows():
    # get lat, lng from df
    lat = row["Latitude"]
    lng = row["Longitude"]

    # change location each iteration while leaving original params in place
    params["location"] = f"{lat},{lng}"

    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # make request and print url
    name_address = requests.get(base_url, params=params)
    
    # convert to json
    name_address = name_address.json()
    
    # Since some data may be missing we incorporate a try-except to skip any that are missing a data point.
    try:
        hotel_df.loc[index, "Hotel Name"]= name_address["results"][0]["name"]
        print(name_address["results"][0]["name"])
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")

Quinta Das Buganvílias
Patagonia B&B
Missing field/result... skipping.
Los Cauquenes Resort & Spa
Hotel Grand Chancellor Hobart
Pebbles Inn
Hôtel Restaurant Sakouli
Old Colony Inn
Bertelli Chuí Hotel
Missing field/result... skipping.
Missing field/result... skipping.
Ellie's Villa
Playa Linda Hotel
Hotel Meuligoe
Oa Oa Lodge
Missing field/result... skipping.
Broadwater Resort
Paradise First Hotel
Missing field/result... skipping.
Splendid Inn Bayshore
Hotel de Casablanca
Nusa Island Retreat
Esperance Seafront Holiday Units
Hotel Madira
Missing field/result... skipping.
Atlanticview Cape Town Boutique Hotel
Best Western Thompson Hotel & Suites
Victoria Hotel - Bredasdorp
Missing field/result... skipping.
Pousada Pura Vida Club Brasil
Pension Maro'i
Hotel Plaza Lebu
Gostinitsa Ip Zabirov
Missing field/result... skipping.
Ahipara Bay Motel
Sofitel Legend Old Cataract Aswan
Mar Guesthouse
DISCOVERY AMBOASARY
Missing field/result... skipping.
THE REDWOOD RIVERWALK HOTEL
Powell River Town Centre Hotel
Hudson New York
Chautauqua Harbor Hotel
Hospitality Carnarvon
Blue Lagoon Hotel
Kolos
Missing field/result... skipping.
Missing field/result... skipping.
Sunset Inn & Suites
Helnan Marselis Hotel
Missing field/result... skipping.
Hotel Shekinah
Missing field/result... skipping.
Hilo Hawaiian Hotel
Missing field/result... skipping.
Sheraton Mar del Plata Hotel
Munitsipal'naya Gostinitsa
Laguna Beach Hotel & Spa
Hilton Barbados Resort
Missing field/result... skipping.
Flamingo Vallarta Hotel & Marina
Hotel da Canoa
Lidotel Hotel Boutique San Cristobal
Heritage Hotel
Mary-Ann's Polarrigg
Missing field/result... skipping.
Edward River Hotel
Missing field/result... skipping.
Hunter's B&B
Kak Doma
Meaford Inn
Arktika
HENRIETA CECÍLIA GASKIN
The Inn at Saint Mary's
Qaanaaq Hotel
Katsuura Hilltop Hotel & Residence
Naujaaraaluit – Clyde River Hotel
Hotel New Amami
ELİTE MY GARDEN OTEL
Hotel Los Caracoles
Hotel Sownthariyam
Steppe hotel
The Harbourview
Missing field/result... skipping.
Sheraton Kauai Resort at Coconut Beach
Kongsvinger Budget Hotel
Lakeview Inns & Suites - Fort Nelson
Desert Gat
Palanca Hotel
Sømandshjemmet
Bugaendrus Paradise
Manek SVASTI Inn
Bem-Vindo Lodge
Shanti Maurice Resort & Spa
Ambassador Hotel
ibis Styles Broken Hill
Simplicité Marquises
Heliopic Hotel & Spa
Zilwa Attitude Hotel
عروس الشاطئ للوحدات السكنية المفروشة
Pousada Kactus
Gostinitsa Kedr
Café de Upernavik
Tourist House - Sablino
The Explorer Hotel
Savana Park Hotel
Sundog Inn
Ocean View Bed & Breakfast
Missing field/result... skipping.
Hotel Tazovchanka
Missing field/result... skipping.
Missing field/result... skipping.
Salaam Hotel
Palissandre Cote Ouest resort & SPA
Hotel Angmagssalik
Quality Inn & Suites
Hotel Kap Farvel
Arctic Chalet LTD
"Aleksandrova Sloboda"
Missing field/result... skipping.
Vista Suites Spa & Golf
Maceió Mar Hotel
Hotel Solymar Galapagos
Hotel Ren
Best Western Hotel Cristallo
Mavuta Manor
Golden Tulip Porto Vitória
Hotel Amenokal
Heia hotel
Prospector Inn
Missing field/result... skipping.
Corrigans Cove Resort
Missing field/result... skipping.
Gornitsa
Missing field/result... skipping.
Ocean Centre Hotel
Jimmy Hotel
Eastern & Oriental Hotel, Penang
Tres Lagunas, Selva Lacandona
Foveaux Hotel
PLAZA HOTEL
Hampton Inn & Suites Cincinnati/Uptown-University Area
Talnakh Hotel
Gostinitsa Rosmorport.
L'oiseau de Paradis
7 on Marine
Bluff Resort Apartments
Hotel Pension Bahnhof
Missing field/result... skipping.
iu Hotel Namibe
Hotel Palacio Arenas
Pond Country Club
Missing field/result... skipping.
Bonthe Holiday Village
HOtel Tasiast
Jalu Hotel
Riyadh Marriott Hotel
Coral Sea Resort & Casino
Missing field/result... skipping.
De Herberg Lodge
Hotel hewa bora
Pinpin d'Amour
Missing field/result... skipping.
Top of the World Hotel
Missing field/result... skipping.
Marriott's Ko Olina Beach Club
Missing field/result... skipping.
TELEGRAPH INN
Don Eddie's Landing
Altayskiye Dachi
ООО "Туруханская пушнина"
Hotel Hiperion Maringá
Liyuan Hotel
Hotel Bela Vista
Missing field/result... skipping.
Villa Nestor
Pousada Liberdade
Budget Guesthouse Borgustova
Sands Hotel Margate
Kwataqnuk Resort & Casino
Waiau Hotel
Missing field/result... skipping.
Hotel Klaksvík
Missing field/result... skipping.
Nino village
Hotel Du Havre
Missing field/result... skipping.
La Josefina Hotel Boutique
Голден Кроун Жуковский
Hotel Punta León
Springbok Inn by Country Hotels
Gostinitsa Dlya Palomnikov
Complexe Hôtelier Du 18 Décembre
The Invisible Hotel — Urban Flashbacks
Missing field/result... skipping.
Four Points by Sheraton Sandakan
Hotel Arctic
Palacio Carrascalino
Hotel Kuber
Hotel Kanjirowa
Missing field/result... skipping.
Bismillah Hotel And Lodging
Codrington Gardens Bed And Breakfast
Best Western Plus Chena River Lodge
Abha Palace Hotel
Inishowen Gateway Hotel
HOTEL TAKUTU
Империя
Hotel Timor
Pensiunea Sophia
The Edgewater Resort and Spa
Hotel Xaguate
Ossora
Missing field/result... skipping.
Turtle Beach By Elegant Hotels
Hotel "Nord House"
Missing field/result... skipping.
La Quinta Inn & Suites by Wyndham Miami Cutler Bay
Hotel S Park In
Seeadler Bay Hotel
Ka'ana Resort And Spa
花しぶき（満開のおもてなし）
Missing field/result... skipping.
Hotel Casa Do Capitão
The Harbour Inn
Inuk Hostels
Hampton Inn Rawlins
A Villa by the Sea
Enchula Resort
Hotel PIEDRA BLANCA
Meijia Jiahua Hotel
Hotel San Jorge Residencial
Missing field/result... skipping.
Missing field/result... skipping.
Wyndham Garden Lake Guntersville
Seagull Hotel
Hotel Gran Palma Talara
Missing field/result... skipping.
Ponta Anchaca
Hotel Buganville Express
Missing field/result... skipping.
Swiss Belhotel Manokwari
Hotel Miramar
Lai Tlang Hotel
Fijnbosch Luxury Apartments Jacobsbaai
Missing field/result... skipping.
Mercure Bengkulu
Hampton Inn Danbury
Embassy Suites by Hilton Lompoc Central Coast
The Ritz-Carlton, Half Moon Bay
Missing field/result... skipping.
Mystic Sands
Hotel Olímpia
InterContinental Bora Bora Resort Thalasso Spa
Hotel Ilha Graciosa
Ludlow Farmstay
ibis budget Dubbo
Missing field/result... skipping.
Welk Resorts Cabo San Lucas
Lofoten Værøy Brygge
The Ravenala Attitude Hotel
Gostinitsa Vodoley
Missing field/result... skipping.
Missing field/result... skipping.
Lakefront Lodge
Untertelshof
Shopping Motel (Adults Only)
Zolotaya Podkova
Lucania Palazzo Hotel
Hotel Olafsvik
Auyuittuq Lodge (Inns North)
Hotel Ekuikui I
Chelelelwa Lode
Kwela Bed & Breakfast
Royal Amazonia
Missing field/result... skipping.
Kafe
Missing field/result... skipping.
Missing field/result... skipping.
Bahay ni Singkit
Hotel almirante
Coral Cay Resort
Hotel Real
Market View Hotel Taveta
Whitsunday Sands Resort
NDN Grand Hotel
Missing field/result... skipping.
Missing field/result... skipping.
Hotel Narsaq
Hampton Inn & Suites Hammond
B&B Torrefano
Hotel Santa Cruz
The Halyards Hotel
Wulingcheng Hotel
Sabzevar Tourism hotel
Romodanovo Saransk Apartment
Hotel Da Vila
Gostinitsa Mup Zhkkh
Hotel Garapacho
iGowati Lodge
REER XOOSHLE GROUP
Missing field/result... skipping.
Missing field/result... skipping.
Frobisher Inn
Missing field/result... skipping.
Hotel Trivento
Gostevoy Dom Demyansk
Hotel Santika Premiere Ambon
Hotel Narendra Palace
Schloss Klafterbrunn
The Trainmaster's Inn
Super Hotel Lohas JR Nara Eki
Happy Palace Hotel
Slobrua Gjestegård
Hotel La Polvora
Hotel Appel
Mariestads Stadshotell
Millbury Guesthouse
Chelpasin
Esplanade Zagreb Hotel
Young Australian Hotel & Function Centre
Aspen Suites Hotel Sitka
Hotel Qaqortoq
Prima Indah Hotel
Missing field/result... skipping.
Missing field/result... skipping.
Shelikof Lodge
Hotel Maritim Skjervøy AS
Hotel Pousada Mineirinho
OYO 119 Jasmine Hotel Apartments
Atlantic Oceanside Hotel & Event Center
Hyatt House San Ramon
Gîtes Makadan (Les)
GreenTree Inn
Arbol
Cressfield Country House Hotel
eSuites Vila do Mar
Laluna Boutique Beach Hotel and Villas
Preskil Island Resort
Dena Hotel
Mountain Hotel
Hiddig Hotel
Hotel Mapuera
Swiss-Belhotel Sorong
Missing field/result... skipping.
Missing field/result... skipping.
Archer Hotel Redmond
Hotel y restaurante "El Diamante"
Samuels Hotel
Adayi Lodge
RAMADA ENCORE BY WYNDHAM SEOUL DONGDAEMUN
Missing field/result... skipping.
Shangri-La Hotel, Hohhot
Missing field/result... skipping.

Best Western Burke and Wills Motor Inn
诚信商务酒店
Gacayte Hotel
Missing field/result... skipping.
Hotel Carabane
Shellharbour Resort & Conference Centre
Hilton Garden Inn Norwalk
Missing field/result... skipping.
Missing field/result... skipping.
The Celtic Manor Resort
Holy Drop Skate House
Holiday Inn Express Campbellsville
Missing field/result... skipping.
Shangri-La Hotel, The Marina, Cairns
Missing field/result... skipping.
Every day Holiday
Hotelli Puustelli
Opuwo Country Lodge
Shapur Hotel
Missing field/result... skipping.
Hotel Maniitsoq
Missing field/result... skipping.
Madina white house hotel
Missing field/result... skipping.
Sea View Hotel
Missing field/result... skipping.
Quality Hotel Mildura Grand
Три Сосны Гостинница
Azalea Luxury Lodge
Hilton Garden Inn Lincoln Downtown/Haymarket
AungKaDay Hotel
Hotel Grot
Bari Hotel
Missing field/result... skipping.
Mövenpick Hotel Qassim
Meieriet Restaurant
Yongchang Hotel
Gostinitsa Zverevo
Missing field/result... skipping.
Inn Gostinnyi Dvor
Hotel Legal
Aleksandar
Puri Brata
Missing field/result... skipping.
Best Western Plus Gold Country Inn
Hotel Tutul Ha
Minosa Resort Hotel
Gostinitsa Grenada
Jinyue International Hotel
Xichang Minshan Hotel
Paradise Bay Resort
Holiday Inn Express & Suites Tooele
Oshen Apartments Yeppoon
Missing field/result... skipping.
Missing field/result... skipping.
Hotel El Mirador
Aridolf Resort Wellness and Spa
Missing field/result... skipping.
Kluane Park Inn
Balance sheet hotel
Missing field/result... skipping.
Plazamar Hotel Boutique
Gran Hotel
Ramada by Wyndham Emerald Park/Regina East
Hôtel Mercure La Baule Majestic
Hotel Pintado Azul
Missing field/result... skipping.
Maison Tait House Restaurant
Missing field/result... skipping.
Red Lion Hotel & Conference Center St. George
Sur Grand Hotel
Bed & Breakfast Sweet Dreams
Kourosh Hotel
Doosti Hotel
ตะลุมพุก ซีฟู้ด แอนด์ รีสอร์ท
Hôtel Opémiska
Missing field/result... skipping.
Ak-El Lokatasi Ciğer Salonu Otel Ve Pansiyon
Aurora Inn & Suites
Maui Beach Hotel
La Posada De Santa Maria
Swiss-Belhotel Palu
Hotel Polo Orchid
Baobab
The Royal House
Vinay Plaza Hotel
Sinclairs Bayview Port Blair
Amiin Hotel
Huis Klipdrift
Pradera Verde
Missing field/result... skipping.
Salalah Gardens Hotel
Acamms Gardens Lodge Mongu
Taloa Heights
Missing field/result... skipping.
Comfort Inn & Suites Augusta Westside
Hôtel Bondo
Sheraton Tucuman Hotel
Hotel Caribe
تفضل بيت ضيافة Geust house tafadal
H10 Las Palmeras
Best Western Holiday Hotel
Missing field/result... skipping.
Glen Lyon Inn
Hotel Mulchén
Missing field/result... skipping.
DoubleTree Suites by Hilton Hotel Lexington
Missing field/result... skipping.
Loulan Hotel
Best Western Plus Montreal Downtown-Hotel Europa
Missing field/result... skipping.
Royal Hotel
Missing field/result... skipping.
Inubosaki Kanko Hotel
Zhemchug
Hotel Folkloro Sanriku Kamaishi
Hôtel SAMAKI Plage
Hondaafushi Island Resort
Pudong Holiday Hotel
Missing field/result... skipping.
Hotel Belle Vue
Mercure Padang
Safir Hotel Doha
Gostevoy Dom S.barguzin "Vizit"
Kairos Cottage
Praia Hotel Imbituba
Apart Hotel Cabaña
Missing field/result... skipping.
Gostinitsa "Viktoriya"
Hotel National
Chatham
Mediterrânea Hotel e Restaurante
Missing field/result... skipping.
Hotel Santoshi Sarovar
Quest Hotel San Denpasar
Hotel Les Cascades
Missing field/result... skipping.
GoldenBay Hotel Bintulu
Milk Factory
Hampton Inn & Suites Cleburne
Missing field/result... skipping.
Hotel Almagre
Bayhaven Lodge
Blue Palace, a Luxury Collection Resort and Spa, Crete
Faial Resort Hotel
Missing field/result... skipping.
BALAJI HOTEL
ОРХІДЕЯ
Maridon Lodge
Wingate By Wyndham Rome
Horizon Inn & Suites
Missing field/result... skipping.
Holiday Inn Express & Suites Sikeston
AmericInn by Wyndham, Merrill
Missing field/result... skipping.
Abacus Motel
Missing field/result... skipping.
Sanatoriy Toktamys
Hôtel Restaurant La Casera
BIG4 Howard Springs Holiday Park
Port Lincoln Hotel
Casa Salcia Oituz
Molino del Corregidor
Tarumã Tropical Hotel
Best Western Plus Chena River Lodge
Grand Hotel Sampit
Oaks Hervey Bay Resort and Spa
Le Battant Des Lames
Lipar Hotel
Hotel Nemuro Kaiyoutei
Hotel Pradomar
SALCAY HOTEL
Shumba Lodge
Missing field/result... skipping.
Casa Rodo 53
Rest Haven Beach Cottages
DoubleTree by Hilton Hotel Milton Keynes
Mini-Hotel Persona
Welcomhotel Kences Palm Beach, Mahabalipuram
Missing field/result... skipping.
ibis Styles Port Hedland
Missing field/result... skipping.
Panamericana Hotel Ancud
Distinction Dunedin Hotel
Gostinitsa "Chulpan"
Chengmao Guojin Hotel
Hospedaje QUIMEY RUCA
Trudvang Apartment Hotel
Marovoay
Hotel & Spa Peñíscola Plaza Suites
Missing field/result... skipping.
Freddies Santai Sumurtiga
La renaissance
Missing field/result... skipping.
Hilton Taizhou
Berlevåg camping & Appartement AS
Paradise Hotel
Hotel Falter Hof
Missing field/result... skipping.
Balihai Bungalows
Hotel Kesh Palace
Hotel Diniz
Hotel Pousada Paraíso
Pousada avenida
Tanna Ikamir Bungalows and Accommodation
Missing field/result... skipping.
Missing field/result... skipping.
Hotel Ayuana
Yeet Hotel
Bohio Dive Resort
Patagonia House
Hotel Atlântico Rio Grande
Missing field/result... skipping.
Grand Hotel - Diamond Palace
Jintai Hotel
Mehamn Arctic Hotel AS
Dolphin Hotel
DoubleTree by Hilton Hotel Alice Springs
Missing field/result... skipping.
OURE TERA beach resort

In [11]:
#Save dataframe as csv
hotel_df.to_csv("Output_csv_files/hotel_output.csv", encoding="utf-8", index=False)
hotel_df.head(20)

              City  Latitude  Longitude                     Hotel Name
0   ribeira grande     38.52     -28.70         Quinta Das Buganvílias
1     punta arenas    -53.15     -70.92                  Patagonia B&B
2        wattegama      6.80      81.48
3          ushuaia    -54.80     -68.30     Los Cauquenes Resort & Spa
4           hobart    -42.88     147.33  Hotel Grand Chancellor Hobart
5        hithadhoo     -0.60      73.08                    Pebbles Inn
6         bandrele    -12.91      45.19       Hôtel Restaurant Sakouli
7      new norfolk    -42.78     147.06                 Old Colony Inn
8             chuy    -33.70     -53.46            Bertelli Chuí Hotel
9       lavrentiya     65.58    -171.00
10      sergeyevka     53.88      67.42
11         mataura    -46.19     168.86                  Ellie's Villa
12        progreso     21.28     -89.67              Playa Linda Hotel
13        meulaboh      4.14      96.13                 Hotel Meuligoe
14         vaitape    -16.52    -151.75                    Oa Oa Lodge
15      baijiantan     45.63      85.18
16       busselton    -33.65     115.33              Broadwater Resort
17           vaini    -21.20    -175.20           Paradise First Hotel
18          albany     42.60     -73.97
19    richards bay    -28.78      32.04          Splendid Inn Bayshore